version: '3'

services:
  backend:
    image: node:12
    working_dir: "/app/backend"
    user: node
    env_file:
      - "env"
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - "../../:/app"
    # command: "npm run dev"
    command: "npm run dev:debug"

  frontend:
    image: node:12
    working_dir: "/app/frontend"
    user: node
    ports:
      - "4200:4200"
    volumes:
      - "../../:/app"
    command: "npm run docker:dev"

  mailer:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
